import os
import json
import base64
import asyncio
import aiohttp
import aiofiles
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.environ.get("MODEL_API_KEY")
API_URL = "https://api.meta.ai/v1/responses"

SYSTEM_PROMPT_TEMPLATE = """You are an expert multimodal AI judge specialized in verifying data extraction and mathematical logic in scientific charts. 

You will be shown a chart image, a question about that chart, and the verified ground truth answer. You will also be given the 'Previous Steps' generated by the student model, and the single 'Current Step' you must evaluate.

Evaluate the 'Current Step' strictly based on the provided chart, the question context, and its logical consistency with the 'Previous Steps'.

**CRITERIA FOR EVALUATION:**
*   **PASS (Score: 1):** The step is completely factually accurate according to the visual data and logically consistent with the previous steps. Any numbers read, colors identified, labels tracked, or math operations performed in this step are 100% correct.
*   **FAIL (Score: 0):** The step contains ANY error. This includes: misreading an axis value, hallucinatory numbers not present on the chart, incorrect arithmetic calculations, or drawing a conclusion that contradicts or misapplies the previous steps. If it makes a mistake, it is an automatic FAIL.

**OUTPUT FORMAT:**
You MUST respond strictly in valid JSON format. Do not include any conversational filler, markdown formatting (like ```json), or explanations outside the JSON object. The "analysis" field must come before the "score" field so you can reason through the step before assigning the final mark.

Ensure your response conforms exactly to this schema:
{{
  "analysis": "A concise 1-2 sentence explanation evaluating the factual correctness of the step based on the chart, and verifying its logical coherence with the previous steps.",
  "score": 1 or 0
}}

---
**INPUT DATA:**
*   **Chart Question:** {QUESTION}
*   **Ground Truth Answer:** {GROUND_TRUTH}
*   **Previous Steps:** {PREVIOUS_STEPS}
*   **Current Step to Evaluate:** {CURRENT_STEP}"""

def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

def build_payload(image_b64, prompt_text):
    return {
        "model": "muse-spark-1.1",
        "input": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": prompt_text
                    },
                    {
                        "type": "input_image",
                        "image_url": f"data:image/jpeg;base64,{image_b64}"
                    }
                ]
            }
        ],
        "stream": False,
    }

async def call_meta_api(session, payload, retries=3):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }
    
    for attempt in range(retries):
        try:
            async with session.post(API_URL, headers=headers, json=payload, timeout=60) as response:
                if response.status == 200:
                    data = await response.json()
                    # Extract the response text
                    output = data.get("output", [])
                    for item in output:
                        if item.get("type") == "message" and item.get("role") == "assistant":
                            content_arr = item.get("content", [])
                            for content in content_arr:
                                if content.get("type") == "output_text":
                                    return content.get("text")
                elif response.status == 429:
                    await asyncio.sleep(2 ** attempt)
                    continue
                else:
                    text = await response.text()
                    print(f"API Error {response.status}: {text}")
                    await asyncio.sleep(2)
        except Exception as e:
            print(f"Request failed: {e}")
            await asyncio.sleep(2)
            
    return None

def extract_json_from_response(response_text):
    if not response_text:
        return None
        
    try:
        # Sometimes models wrap in markdown
        if "```json" in response_text:
            response_text = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```")[1].split("```")[0].strip()
            
        return json.loads(response_text)
    except json.JSONDecodeError:
        return None

async def worker(queue, session, write_queue, semaphore):
    while True:
        task = await queue.get()
        if task is None:
            break
            
        (q_id, rollout_idx, step_idx, image_path, prompt_text, original_data) = task
        
        async with semaphore:
            image_b64 = encode_image(image_path)
            payload = build_payload(image_b64, prompt_text)
            
            response_text = await call_meta_api(session, payload)
            parsed_json = extract_json_from_response(response_text)
            
            result = {
                "question_id": q_id,
                "rollout_index": rollout_idx,
                "step_index": step_idx,
                "evaluation": parsed_json,
                "raw_response": response_text
            }
            
            await write_queue.put(result)
            
        queue.task_done()

async def writer_task(write_queue, output_file):
    async with aiofiles.open(output_file, mode='a', encoding='utf-8') as f:
        while True:
            result = await write_queue.get()
            if result is None:
                break
            await f.write(json.dumps(result, ensure_ascii=False) + '\n')
            await f.flush() # Intermediate saving instantly to disk
            write_queue.task_done()

async def main_async(input_file, output_file, image_dir, concurrency=20):
    # Determine already processed tasks to skip them
    processed = set()
    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    data = json.loads(line)
                    # Unique identifier for a step
                    ident = f"{data['question_id']}_{data['rollout_index']}_{data['step_index']}"
                    processed.add(ident)
                    
    queue = asyncio.Queue()
    write_queue = asyncio.Queue()
    
    tasks_to_do = 0
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            q_id = str(data["question_id"])
            rollout_idx = data["rollout_index"]
            question = data["question"]
            gt = data["ground_truth"]
            steps = data["parsed_steps"]
            
            image_path = os.path.join(image_dir, f"{q_id}.jpg")
            if not os.path.exists(image_path):
                continue
                
            for step_idx, current_step in enumerate(steps):
                ident = f"{q_id}_{rollout_idx}_{step_idx}"
                if ident in processed:
                    continue
                    
                previous_steps_str = "\n".join(steps[:step_idx]) if step_idx > 0 else "None"
                
                prompt = SYSTEM_PROMPT_TEMPLATE.format(
                    QUESTION=question,
                    GROUND_TRUTH=gt,
                    PREVIOUS_STEPS=previous_steps_str,
                    CURRENT_STEP=current_step
                )
                
                queue.put_nowait((q_id, rollout_idx, step_idx, image_path, prompt, data))
                tasks_to_do += 1
                
    print(f"Tasks to process: {tasks_to_do}")
    if tasks_to_do == 0:
        return
        
    semaphore = asyncio.Semaphore(concurrency)
    
    async with aiohttp.ClientSession() as session:
        # Start writer
        writer = asyncio.create_task(writer_task(write_queue, output_file))
        
        # Start workers
        workers = [asyncio.create_task(worker(queue, session, write_queue, semaphore)) for _ in range(concurrency)]
        
        # Wait for all items in queue to be processed
        await queue.join()
        
        # Stop workers
        for _ in range(concurrency):
            await queue.put(None)
        await asyncio.gather(*workers)
        
        # Stop writer
        await write_queue.join()
        await write_queue.put(None)
        await writer
        
if __name__ == "__main__":
    INPUT_FILE = "experiments/001_500_reasoning/data/001_500_reasoning_cleaned.jsonl"
    OUTPUT_FILE = "experiments/001_500_reasoning/data/evaluated_steps.jsonl"
    IMAGE_DIR = "data/CharXiv/images"
    
    asyncio.run(main_async(INPUT_FILE, OUTPUT_FILE, IMAGE_DIR))
