"""
evaluate_rollouts_meta.py

This script is the core PRM Judge pipeline. It asynchronously calls the Meta API (`muse-spark-1.1`) 
to evaluate the reasoning rollouts for the PRM dataset. To heavily optimize API token costs, it groups 
all reasoning steps for a single rollout into one API call (Rollout-Level Batching) and resizes 
images to a maximum of 512px before encoding them to Base64.
"""
import os
import json
import base64
import asyncio
import aiohttp
import aiofiles
import time
import argparse
import io
from PIL import Image
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.environ.get("MODEL_API_KEY")
API_URL = "https://api.meta.ai/v1/responses"

SYSTEM_PROMPT_TEMPLATE = """You are an expert multimodal AI judge specialized in verifying data extraction and mathematical logic in scientific charts. 

You will be shown a chart image, a question about that chart, and the verified ground truth answer. You will also be given the 'Steps' generated by a student model. Evaluate EVERY step in the list sequentially, strictly based on the provided chart, the question context, and its logical consistency with the previous steps.

**CRITERIA FOR EVALUATION:**
*   **PASS (Score: 1):** The step is completely factually accurate according to the visual data and logically consistent with the preceding steps. Any numbers read, colors identified, labels tracked, or math operations performed in this step are 100% correct.
*   **FAIL (Score: 0):** The step contains ANY error. This includes: misreading an axis value, hallucinatory numbers not present on the chart, incorrect arithmetic calculations, or drawing a conclusion that contradicts or misapplies the preceding steps. If it makes a mistake, it is an automatic FAIL.

**OUTPUT FORMAT:**
You MUST respond strictly in valid JSON format, returning a JSON array of evaluation objects. Do not include any conversational filler, markdown formatting (like ```json), or explanations outside the JSON array. The "analysis" field must come before the "score" field. 

Ensure your response conforms exactly to this schema:
[
  {{
    "step_index": 0,
    "analysis": "A concise 1-2 sentence explanation evaluating the factual correctness of Step 0 based on the chart, and verifying its logical coherence.",
    "score": 1 or 0
  }},
  {{
    "step_index": 1,
    "analysis": "A concise 1-2 sentence explanation evaluating the factual correctness of Step 1 based on the chart, and verifying its logical coherence with previous steps.",
    "score": 1 or 0
  }}
]

---
**INPUT DATA:**
*   **Chart Question:** {QUESTION}
*   **Ground Truth Answer:** {GROUND_TRUTH}
*   **Steps to Evaluate:**
{STEPS}"""

def encode_image(image_path, max_size=512):
    # Resize the image to save on input tokens while maintaining enough resolution
    with Image.open(image_path) as img:
        img.thumbnail((max_size, max_size))
        
        # Convert to RGB if it's RGBA
        if img.mode == 'RGBA':
            img = img.convert('RGB')
            
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG")
        return base64.b64encode(buffer.getvalue()).decode('utf-8')

def build_payload(image_b64, prompt_text):
    return {
        "model": "muse-spark-1.1",
        "input": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": prompt_text
                    },
                    {
                        "type": "input_image",
                        "image_url": f"data:image/jpeg;base64,{image_b64}"
                    }
                ]
            }
        ],
        "stream": False,
    }

async def call_meta_api(session, payload, retries=3):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }
    
    for attempt in range(retries):
        try:
            async with session.post(API_URL, headers=headers, json=payload, timeout=90) as response:
                if response.status == 200:
                    data = await response.json()
                    output = data.get("output", [])
                    for item in output:
                        if item.get("type") == "message" and item.get("role") == "assistant":
                            content_arr = item.get("content", [])
                            for content in content_arr:
                                if content.get("type") == "output_text":
                                    return content.get("text")
                elif response.status == 429:
                    await asyncio.sleep(2 ** attempt)
                    continue
                else:
                    text = await response.text()
                    print(f"API Error {response.status}: {text}")
                    await asyncio.sleep(2)
        except Exception as e:
            print(f"Request failed: {e}")
            await asyncio.sleep(2)
            
    return None

def extract_json_array_from_response(response_text):
    if not response_text:
        return None
        
    try:
        if "```json" in response_text:
            response_text = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```")[1].split("```")[0].strip()
            
        parsed = json.loads(response_text)
        if isinstance(parsed, list):
            return parsed
        elif isinstance(parsed, dict) and "evaluations" in parsed:
            return parsed["evaluations"]
        return None
    except json.JSONDecodeError:
        return None

async def worker(queue, session, write_queue, semaphore):
    while True:
        task = await queue.get()
        if task is None:
            break
            
        (q_id, rollout_idx, image_path, prompt_text, original_data) = task
        
        async with semaphore:
            image_b64 = encode_image(image_path)
            payload = build_payload(image_b64, prompt_text)
            
            response_text = await call_meta_api(session, payload)
            parsed_json = extract_json_array_from_response(response_text)
            
            result = {
                "question_id": q_id,
                "rollout_index": rollout_idx,
                "evaluations": parsed_json,
                "raw_response": response_text
            }
            
            await write_queue.put(result)
            
        queue.task_done()

async def writer_task(write_queue, output_file, total_tasks):
    start_time = time.time()
    processed = 0
    async with aiofiles.open(output_file, mode='a', encoding='utf-8') as f:
        while True:
            result = await write_queue.get()
            if result is None:
                break
            await f.write(json.dumps(result, ensure_ascii=False) + '\n')
            await f.flush()
            
            processed += 1
            elapsed = time.time() - start_time
            rate = processed / elapsed if elapsed > 0 else 0
            print(f"[{processed}/{total_tasks}] Saved rollout {result['question_id']}_{result['rollout_index']} (Speed: {rate:.2f} rollouts/s, Elapsed: {elapsed:.1f}s)")
            
            write_queue.task_done()

async def main_async(input_file, output_file, image_dir, concurrency=20, max_rollouts=None):
    processed = set()
    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    data = json.loads(line)
                    ident = f"{data['question_id']}_{data['rollout_index']}"
                    processed.add(ident)
                    
    queue = asyncio.Queue()
    write_queue = asyncio.Queue()
    
    tasks_to_do = 0
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
            data = json.loads(line)
            q_id = str(data["question_id"])
            rollout_idx = data["rollout_index"]
            question = data["question"]
            gt = data["ground_truth"]
            steps = data["parsed_steps"]
            
            ident = f"{q_id}_{rollout_idx}"
            if ident in processed:
                continue
                
            image_path = os.path.join(image_dir, f"{q_id}.jpg")
            if not os.path.exists(image_path):
                continue
                
            steps_str = ""
            for i, step in enumerate(steps):
                steps_str += f"Step {i}: {step}\n"
                
            prompt = SYSTEM_PROMPT_TEMPLATE.format(
                QUESTION=question,
                GROUND_TRUTH=gt,
                STEPS=steps_str.strip()
            )
            
            queue.put_nowait((q_id, rollout_idx, image_path, prompt, data))
            tasks_to_do += 1
            if max_rollouts is not None and tasks_to_do >= max_rollouts:
                break
                
    print(f"Rollouts to process: {tasks_to_do}")
    if tasks_to_do == 0:
        return
        
    start_time = time.time()
    semaphore = asyncio.Semaphore(concurrency)
    
    async with aiohttp.ClientSession() as session:
        writer = asyncio.create_task(writer_task(write_queue, output_file, tasks_to_do))
        workers = [asyncio.create_task(worker(queue, session, write_queue, semaphore)) for _ in range(concurrency)]
        
        await queue.join()
        
        for _ in range(concurrency):
            await queue.put(None)
        await asyncio.gather(*workers)
        
        await write_queue.join()
        await write_queue.put(None)
        await writer
        
    total_time = time.time() - start_time
    print(f"\nCompleted {tasks_to_do} rollouts in {total_time:.2f} seconds.")
    if tasks_to_do > 0:
        print(f"Average speed: {tasks_to_do / total_time:.2f} rollouts/second.")
        
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate full rollouts using Meta API")
    parser.add_argument("--max-rollouts", type=int, default=None, help="Maximum number of rollouts to process")
    args = parser.parse_args()
    
    INPUT_FILE = "experiments/001_500_reasoning/data/001_500_reasoning_cleaned.jsonl"
    OUTPUT_FILE = "experiments/001_500_reasoning/data/evaluated_rollouts.jsonl"
    IMAGE_DIR = "data/CharXiv/images"
    
    asyncio.run(main_async(INPUT_FILE, OUTPUT_FILE, IMAGE_DIR, max_rollouts=args.max_rollouts))
